apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "configmaps", "secrets"]  
  verbs: ["get", "list", "watch", "create", "update", "delete"]  
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: default
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app  
    spec:    
      containers:
        - name: my-react-app-container
          image: anuruddhakhare/app:latest
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-srv
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - name: my-app
      port: 8000
