name: my-workflow
'on': push
jobs:
  create-image-and-push-to-dockerhub:
    name: Create Image and Push to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ Anuruddhakhare99 }}
          password: ${{ Anuruddhakhare99 }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: niranjang2/book-management-app:${{ github.sha }}
          build-args: REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}
